export const getColors = () => [
    {name: 'aqua', found: false, error: false, disabled: false, squareClassName: '', textClassName: ''},
    {name: 'brown', found: false, error: false, disabled: false, squareClassName: '', textClassName: ''},
    {name: 'black', found: false, error: false, disabled: false, squareClassName: '', textClassName: ''},
    {name: 'chocolate', found: false, error: false, disabled: false, squareClassName: '', textClassName: ''},
    {name: 'coral', found: false, error: false, disabled: false, squareClassName: '', textClassName: ''},
    {name: 'azure', found: false, error: false, disabled: false, squareClassName: '', textClassName: ''},
    {name: 'beige', found: false, error: false, disabled: false, squareClassName: '', textClassName: ''},
    {name: 'bisque', found: false, error: false, disabled: false, squareClassName: '', textClassName: ''},
    {name: 'blue', found: false, error: false, disabled: false, squareClassName: '', textClassName: ''},
    {name: 'tan', found: false, error: false, disabled: false, squareClassName: '', textClassName: ''},
    {name: 'cornsilk', found: false, error: false, disabled: false, squareClassName: '', textClassName: ''},
    {name: 'cyan', found: false, error: false, disabled: false, squareClassName: '', textClassName: ''},
    {name: 'gold', found: false, error: false, disabled: false, squareClassName: '', textClassName: ''},
    {name: 'gray', found: false, error: false, disabled: false, squareClassName: '', textClassName: ''},
    {name: 'pink', found: false, error: false, disabled: false, squareClassName: '', textClassName: ''},
    {name: 'indigo', found: false, error: false, disabled: false, squareClassName: '', textClassName: ''},
    {name: 'ivory', found: false, error: false, disabled: false, squareClassName: '', textClassName: ''},
    {name: 'khaki', found: false, error: false, disabled: false, squareClassName: '', textClassName: ''},
    {name: 'lavender', found: false, error: false, disabled: false, squareClassName: '', textClassName: ''},
    {name: 'teal', found: false, error: false, disabled: false, squareClassName: '', textClassName: ''},
    {name: 'linen', found: false, error: false, disabled: false, squareClassName: '', textClassName: ''},
    {name: 'magenta', found: false, error: false, disabled: false, squareClassName: '', textClassName: ''},
    {name: 'maroon', found: false, error: false, disabled: false, squareClassName: '', textClassName: ''},
    {name: 'moccasin', found: false, error: false, disabled: false, squareClassName: '', textClassName: ''},
    {name: 'orchid', found: false, error: false, disabled: false, squareClassName: '', textClassName: ''}
];